FROM node:16.20-slim

WORKDIR /var/server/

COPY package.json package-lock.json ./

RUN npm ci

COPY tsconfig.json nodemon.json ./
COPY src/ ./src/

ARG PORT
ENV APP_PORT=$PORT

CMD [ "npm", "run", "dev" ]
